jobs:
  include:
  - stage: test
    language: java
    jdk: oraclejdk8
    install: true
    script:
    - "./mvnw test"
    cache:
      directories:
      - "$HOME/.m2"
  - stage: build
    language: java
    jdk: oraclejdk8
    install: true
    script:
    - "./mvnw clean package -DskipTests"
    cache:
      directories:
      - "$HOME/.m2"
  - stage: deploy to staging heroku
    if: branch = master
    language: java
    jdk: oraclejdk8
    cache:
      directories:
      - "$HOME/.m2"
    deploy:
      provider: heroku
      api_key:
        secure: HwI/y5Ow/LsuAAaNFfLyJgedmfyrj1utl9uzqKgI8TcxdIOGCb9Ws2tR2/i023EC9vVqrr2NsNKevOHamGEEd3c+AxpfVI+LOux/wGdRfKGZDAehVgyo3xObYapPj6trQ4XAXnN1If0XUy7nxtJQ1ToSu5UbH6RjX8Uhz9+9aF9Ekh/4H415u3P4+TBj15H8XSBLgm5ZuwydsLwPQme7NYe5zna3Xkjmaevq4xQNgtGd68b9FPUd2PBgY+dLM+aDZUMUWfTneAA5yxRhUX0N9riXmR00x4ZIsXTWJKP7HSDVS9gs3f1hks2A6a9BgkmuXzcApo310xdWn0SfUMiHdAjNFngW6Q6bZxRLhQyP0nBd1qlvBjut3LGopi2fNBMxUxQOzAscI2vkhNB6Qpv93uScZ8zjVK8wXx2osKr3UuAcSbb9fTkccQ3Jm5dujlqdRS1qktoSBhEXhxsONk4awGlkbSjNFULQibIYBP7TTyWpDSZ2j+NEhI+1Lknch0V6APRXmBqw+4TheWNvrupfuFZBxW4c5SikxjAMGduXr8el1dd6MlsaDZykPaVtwVds2ivEPGy9Xp038LSILkoGY+sFVPoIJ/M67fuBUDgGK6NBgTm2kgaO1KtU0FisaTnV8DNThyy1Bhz2bKmYZGR6hLrR5ImkPispXjJM6YVX1xc=
      app: redis-monitoring-java-vue
      on:
        repo: ivandzf/redis-monitoring
        branch: master
  - stage: test staging
    if: branch = master
    script: curl https://redis-monitoring-java-vue.herokuapp.com/
